language: go

go:
 - 1.8

install:
 - go get github.com/boltdb/bolt

script:
 - go test -v -covermode=count -coverprofile=coverage.out
$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
